version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"      # Location of your workflow files
    schedule:
      interval: "monthly"  # Options: daily, weekly, monthly
    groups:
      actions:
        patterns:
          - "*"
