version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-4.10"

conda:
  environment: docs/rtd_environment.yaml

sphinx:
  builder: html
  configuration: docs/conf.py

# Install regular dependencies.
# Then, install special pinning for RTD.
python:
  system_packages: false
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

# Don't build any extra formats
formats: []
