version: 2

build:
  os: "ubuntu-22.04"

sphinx:
  builder: html
  configuration: docs/conf.py

python:
  system_packages: false
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

# Don't build any extra formats
formats: []
