name: CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
      - '!*dev*'
      - '!*pre*'
      - '!*post*'
  pull_request:
  # Allow manual runs through the web UI
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      libraries: |
        apt:
          - ghostscript
          - inkscape
      envs: |
        # Test oldest SPEC 0 configurations
        - linux: py311-test-mpl37
        - macos: py311-test-mpl37
        - windows: py311-test-mpl37
        # Test newest configurations
        - linux: py313-test-mpl39
        - macos: py313-test-mpl39
        - windows: py313-test-mpl39
        # Test intermediate SPEC 0 configurations on Linux
        - linux: py312-test-mpl37
        - linux: py311-test-mpl38
        - linux: py313-test-mpl38
        - linux: py312-test-mpl39
        # Test non-SPEC 0 configurations
        - linux: py313-test-mpldev-pytestdev
        - linux: py311-test-mpl37-pytest74
        - linux: py39-test-mpl33-pytest62
        - linux: py37-test-mpl22-pytest54
          runs-on: ubuntu-22.04
      coverage: 'codecov'

  publish:
    if: github.event_name != 'pull_request'
    needs: [test]
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish_pure_python.yml@v1
    with:
      test_command: pytest $GITHUB_WORKSPACE/tests; pytest --mpl $GITHUB_WORKSPACE/tests
    secrets:
      pypi_token: ${{ secrets.pypi_password }}
